name: Check Slots

on:
  schedule:
    # Runs every 6 minutes (GitHub Actions can delay 5-min schedules)
    - cron: '*/6 * * * *'
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main # Keeps workflow active

jobs:
  run_checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install libraries
        run: pip install -r requirements.txt
      
      - name: Run Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID_TARAS: ${{ secrets.TELEGRAM_CHAT_ID_TARAS }}
          TELEGRAM_CHAT_ID_SOFIIA: ${{ secrets.TELEGRAM_CHAT_ID_SOFIIA }}
        run: python main.py
